# Generated by Django 3.0.5 on 2020-04-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200419_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='placas',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
